### ISSUE TITLE
Integration with CSI storage

### ISSUE THREAD

**Issue by mfordjody** [apache/dubbo-kubernetes#41]
- [x] I have searched the [issues](https://github.com/apache/dubbo-kubernetes/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-kubernetes/blob/master/README.md) of this repository and believe that this is not a duplicate.

### Is your feature request related to a problem? Please describe.
Incorporate charts distributed storage system capabilities. Integrate the Rook distributed storage solution into the cluster to provide persistent storage support for containerized applications.

### Why is this Feature Needed

Storage Management: Managing distributed storage systems is typically a complex task, involving node management, data distribution, backups, and fault handling, among others, which can be simplified.

Compliance with CSI Standard: The standard Container Storage Interface (CSI) enables containerized applications to seamlessly access and manage storage without needing to understand the underlying details of the storage system.

Data Persistence: Data can be retained even if containers are restarted or migrated.

Across Clouds and Hybrid Cloud: Deploying or migrating containerized applications between different cloud providers, making it well-suited for organizations with multi-cloud strategies or hybrid cloud deployment requirements.

RBD
```
rbd:
      monitors:
      - 10.100.51.74:6789
      pool: rook-rbd
      image: demo
      fsType: ext4
      user: csi-rbd-node
      secretRef:
        name: ceph-secret
```

CephFS
```
cephfs:
      monitors:
      - 10.100.51.74:6789
      path: /
      user: csi-cephfs-node
      secretRef:
        name: ceph-secret
```

S3
```
gateway:
    sslCertificateRef:
    port: 80
    instances: 2
```

SNAPSHOT
```
source:
    persistentVolumeClaimName:  <rbd-pvc>  # cephfs-pvc
```

### Contribute Feature
I have experience using Rook in a large-scale production environment, enabling users to deploy and manage distributed storage systems more easily. Through Rook integration, I aim to provide users with a comprehensive containerized storage solution to meet the needs of their applications.

### Additional context
If there is any additional information or supplementary content, I would be happy to hear and consider it. I hope this feature will bring greater value to the project and the community.
