### ISSUE TITLE
no matches for kind "VirtualService" in version "service.dubbo.apache.org/v1alpha1"

### ISSUE THREAD

**Issue by tom055** [apache/dubbo-kubernetes#692]
```
apiVersion: service.dubbo.apache.org/v1alpha1
kind: VirtualService
metadata:
  name: k8s-provider-vs
  namespace: dubbo-app
spec:
  hosts:
    - k8s-provider.dubbo-app.svc.cluster.local
  http:
    - route:
      - destination:
          host: k8s-provider
          subset: v1
        weight: 1
      - destination:
          host: k8s-provider
          subset: v2
        weight: 99
```

dubbo-service-version.yaml": no matches for kind "VirtualService" in version "service.dubbo.apache.org/v1alpha1"
